# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

simulateCombat <- function(nReps = 10000L, type = 'c', a_BS = 0L, a_damageDie = 10L, a_damageModifier = 0L, a_penetration = 0L, a_rateOfFire = 1L, d_T = 0L, d_wounds = 0L, d_armour = 0L, d_dodge = 0L, d_forceField = 0L, d_forceFieldOverload = 0L, d_isForceFieldOverloaded = 0L) {
    .Call(`_MSMonteCarlo_simulateCombat`, nReps, type, a_BS, a_damageDie, a_damageModifier, a_penetration, a_rateOfFire, d_T, d_wounds, d_armour, d_dodge, d_forceField, d_forceFieldOverload, d_isForceFieldOverloaded)
}

