// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// simulateCombat
double simulateCombat(int nReps, char type, int a_BS, int a_damageDie, int a_damageModifier, int a_penetration, int a_rateOfFire, int d_T, int d_wounds, int d_armour, int d_dodge, int d_forceField, int d_forceFieldOverload, bool d_isForceFieldOverloaded);
RcppExport SEXP _MSMonteCarlo_simulateCombat(SEXP nRepsSEXP, SEXP typeSEXP, SEXP a_BSSEXP, SEXP a_damageDieSEXP, SEXP a_damageModifierSEXP, SEXP a_penetrationSEXP, SEXP a_rateOfFireSEXP, SEXP d_TSEXP, SEXP d_woundsSEXP, SEXP d_armourSEXP, SEXP d_dodgeSEXP, SEXP d_forceFieldSEXP, SEXP d_forceFieldOverloadSEXP, SEXP d_isForceFieldOverloadedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nReps(nRepsSEXP);
    Rcpp::traits::input_parameter< char >::type type(typeSEXP);
    Rcpp::traits::input_parameter< int >::type a_BS(a_BSSEXP);
    Rcpp::traits::input_parameter< int >::type a_damageDie(a_damageDieSEXP);
    Rcpp::traits::input_parameter< int >::type a_damageModifier(a_damageModifierSEXP);
    Rcpp::traits::input_parameter< int >::type a_penetration(a_penetrationSEXP);
    Rcpp::traits::input_parameter< int >::type a_rateOfFire(a_rateOfFireSEXP);
    Rcpp::traits::input_parameter< int >::type d_T(d_TSEXP);
    Rcpp::traits::input_parameter< int >::type d_wounds(d_woundsSEXP);
    Rcpp::traits::input_parameter< int >::type d_armour(d_armourSEXP);
    Rcpp::traits::input_parameter< int >::type d_dodge(d_dodgeSEXP);
    Rcpp::traits::input_parameter< int >::type d_forceField(d_forceFieldSEXP);
    Rcpp::traits::input_parameter< int >::type d_forceFieldOverload(d_forceFieldOverloadSEXP);
    Rcpp::traits::input_parameter< bool >::type d_isForceFieldOverloaded(d_isForceFieldOverloadedSEXP);
    rcpp_result_gen = Rcpp::wrap(simulateCombat(nReps, type, a_BS, a_damageDie, a_damageModifier, a_penetration, a_rateOfFire, d_T, d_wounds, d_armour, d_dodge, d_forceField, d_forceFieldOverload, d_isForceFieldOverloaded));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MSMonteCarlo_simulateCombat", (DL_FUNC) &_MSMonteCarlo_simulateCombat, 14},
    {NULL, NULL, 0}
};

RcppExport void R_init_MSMonteCarlo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
